[[headers]]
  for = "*.avif"
  [headers.values]
    Content-Type = "image/avif"
    Content-Disposition = "inline"

[[headers]]
  for = "/sw.js"
  [headers.values]
    cache-control = "max-age=0,no-cache,no-store,must-revalidate"

[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = [ ".cache" ]
